### ISSUE TITLE
Does the WSB provide any SDK or API?

### ISSUE THREAD

**Issue by danyhm** [microsoft/Windows-Sandbox#35]
Hello,

I've been recently looking for a program that virtualizes a single app without needing to boot a complete VM.

WSB is the closest I've found but it lacks many features like the sandbox is cleaned at every launch and also APIs like https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/hypervisor-platform for windows hypervisor platform are not available. the thing I want to change is the CPUID return values in the VM Exit handler and WHP provides that API but it's a complete VM that has to be booted.

do you guys have any plans for adding such features?

**Comment by kavyamsft** [comment]
I know it’s been some time, but the latest Windows Sandbox app (now available to Canary and select Dev Channel Windows Insiders) includes an early version of our command-line interface. We don't support an API or SDK currently.
