### ISSUE TITLE
Sandbox for windows 11

### ISSUE THREAD

**Issue by modz2014** [microsoft/Windows-Sandbox#40]
hi i was wondering about gettings sand box for windows 11 on windows 10 I have been looking into this I see a lot of people wanting to run sandbox on windows 10 but with windows 11 its a good way of developing apps for both windows 11 and windows 10
```[tasklist]
### Tasks
- [ ] adding support to run windows 11 on windows 10
- [ ] including netframework and net 5.0 or latest version
```

**Comment by kevincrans** [comment]
I think that would require a lot of effort.
Support for older versions would be easier.

**Comment by modz2014** [comment]
not really it is if know source code about them

**Comment by kavyamsft** [comment]
Unfortunately, we can only support the Host OS build that is currently on your device. This allows us to keep Sandbox 'lightweight'.

**Comment by kavyamsft** [comment]
Unfortunately, we can only support the Host OS build that is currently on your device. This allows us to keep Sandbox 'lightweight'.

**Comment by kavyamsft** [comment]
Unfortunately, we can only support the Host OS build that is currently on your device. This allows us to keep Sandbox 'lightweight'.
