### ISSUE TITLE
Windows Sandbox Editor is malaware for Windows Defender

### ISSUE THREAD

**Issue by no-e-in** [microsoft/Windows-Sandbox#41]
Detected: Trojan:Script/Phonzy.A!ml.
For [VirusTotal](https://www.virustotal.com/gui/file/cde29a4fd40c984d7201f1360cf2d489343732262326a08f1b0b92b35ee2cdb1) 36/71 security vendors and no sandboxes flagged this file as malicious

**Comment by kavyamsft** [comment]
Thanks for letting us know!
