### ISSUE TITLE
[Bug]: Sandbox does not support COM+ Applications

### ISSUE THREAD

**Issue by bevanweiss** [microsoft/Windows-Sandbox#47]
### Windows Sandbox version

Version 10.0.22621.3672

### Windows build number

Microsoft Windows [Version 10.0.22621.3880]

### Steps to reproduce the bug

COM+ Applications rely on basic COM+ services being available to allow for them to be registered (Partitions, applications, roles, users, groups etc configured).

It appears that the COM+ System Application service is unavailable within the Sandbox environment, even though it is operational in the host environment.
When attempting to start the COM+ System Application service within the Sandbox, an `Error 1075; The dependency service does not exist or has been marked for deletion.` is returned.

![image](https://github.com/user-attachments/assets/4c888847-76de-42ee-b53c-e4e9c6361073)

### Expected result

COM+ System Application service would execute similar to in the host environment

### Actual result

Error 1075: The dependency service does not exist or has been marked for deletion, when attempting to start service.

**Comment by kavyamsft** [comment]
@bevanweiss , thanks for reaching out!  The build that you are on doesn't support COM+ Applications. The support for this has been added to Builds 26100+.  You can join the Canary and Dev Channels to get access to these builds today.

**Comment by bevanweiss** [comment]
> @bevanweiss , thanks for reaching out! The build that you are on doesn't support COM+ Applications. The support for this has been added to Builds 26100+. You can join the Canary and Dev Channels to get access to these builds today.

Wonderful, thanks for that.
Do you know if it would also support COM+ Partitions (which is a Windows Server only feature... but it would be incredibly useful to test it under a Windows Desktop OS)?
Also, I know this next one isn't Sandbox related at all, but I've found what I believe to be a bug in the COM Registration of the RegistrationHelper class under .NET Framework 4.5.  Is there a location where I could best report this issue?

**Comment by kavyamsft** [comment]
We do not support COM+ partitions. Windows Sandbox only supports (most) features available on client Windows. 

Regarding COM bugs, Feedback Hub is the best place to file bugs in general.
