### ISSUE TITLE
[Feature request] run several instances of Windows Sandbox simultaneously on Windows

### ISSUE THREAD

**Issue by ohault** [microsoft/Windows-Sandbox#49]

**Comment by kavyamsft** [comment]
Thanks for your suggestion! We’ll review it as we prioritize future updates.

**Comment by ohault** [comment]
Hello, this issue is not closed at all. Can you please re-opened this ticket because this will stay a feature request and not a suggestion as long as this feature has not been fully  implemented. Thank you.

**Comment by Ghxst** [comment]
I would really appreciate this feature, to me it's quite important to be able to run programs side by side in real-time and in clean environments, Windows Sandbox is almost perfect for this. Could you please share what the technical limitations are to this feature @kavyamsft ?

**Comment by gerneio** [comment]
FYI, theoretically it's possible and somewhat already baked in (with some major caveats). See my research here:

https://github.com/gerneio/WindowsSandboxPlayground

**Comment by ohault** [comment]
Hi @gerneio, you have just done an amazing documentation effort and very great discoveries, congratulations. After more than 10 years, containers on Windows could perhaps really take off!
