### ISSUE TITLE
[Feature request] integrate Windows Sandbox into Azure Stack, Azure Linux and Windows Server. 

### ISSUE THREAD

**Issue by ohault** [microsoft/Windows-Sandbox#51]

**Comment by kavyamsft** [comment]
Thanks for your suggestion! We’ll review it as we prioritize future updates.

**Comment by ohault** [comment]
Hello, this issue is not closed at all. Can you please re-opened this ticket because this will stay a feature request and not a suggestion as long as this feature has not been fully  implemented. Thank you.
